### ISSUE TITLE
Revert boot sequence

### ISSUE THREAD

**Issue by drcolula** [hcfman/sbts-boot-from-SSD#3]
Is there a way to restore the original boot sequence for a jetson NX? I need to replace the SSD, so I need the device to boot from the SD card as it was originally.

**Comment by hcfman** [comment]
Yes. Run

cd bin
sudo  ./make_orig.sh

And then reboot

That puts back the original boot file in /boot/extlinux



- Cheers
Kim

**Comment by hcfman** [comment]
Sorry

cd sbts-bin
sudo ./make_orig.sh
sudo reboot

- Kim
